tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#e5feff",
        "primary-fixed": "#d8e2ff",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#003739",
        "secondary": "#306388",
        "on-tertiary-container": "#93f8ff",
        "background": "#e5feff",
        "on-secondary-fixed": "#001e31",
        "on-secondary": "#ffffff",
        "surface-container-low": "#cbfdff",
        "surface-container-high": "#b5f3f6",
        "on-surface": "#002021",
        "error": "#ba1a1a",
        "secondary-fixed": "#cce5ff",
        "surface-container": "#bbf9fc",
        "surface-bright": "#e5feff",
        "on-error-container": "#93000a",
        "tertiary-container": "#007479",
        "surface-container-highest": "#afedf0",
        "secondary-fixed-dim": "#9bccf6",
        "on-background": "#002021",
        "on-primary-container": "#e0e8ff",
        "inverse-primary": "#adc6ff",
        "inverse-on-surface": "#bdfcff",
        "surface-dim": "#a7e5e8",
        "on-primary": "#ffffff",
        "outline-variant": "#c3c6d4",
        "on-surface-variant": "#424752",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001a41",
        "tertiary": "#00595e",
        "outline": "#737783",
        "on-tertiary-fixed": "#002022",
        "on-primary-fixed-variant": "#004494",
        "surface-variant": "#afedf0",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#65d7de",
        "secondary-container": "#a4d4ff",
        "primary-fixed-dim": "#adc6ff",
        "primary": "#054da4",
        "on-secondary-container": "#285c81",
        "on-secondary-fixed-variant": "#104b6e",
        "primary-container": "#3066be",
        "on-tertiary-fixed-variant": "#004f53",
        "tertiary-fixed": "#84f4fb",
        "surface-tint": "#225cb3"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
};